fix colours

diff --git a/mts_convert b/mts_convert
--- a/mts_convert
+++ b/mts_convert
@@ -5,6 +5,8 @@ VERBOSE=true
 DRY_RUN=false
 
 INPUT_FILE_NAME='';
+
+OUTPUT_DIR_NAME='./';
 OUTPUT_FILE_NAME='';
 CONFIG_FILE_NAME='';
 
@@ -77,16 +79,18 @@ handle_profile(){
     local suffix=$(profile_default "${name,,}" "$name" 'suffix');
     local passes=$(profile_default '1' "$name" 'passes');
     local format=$(profile_default 'mp4' "$name" 'format');
-    local output=$(compute_if_empty \
+    local output_out_file_name=$(compute_if_empty \
         "${OUTPUT_FILE_NAME}" \
         "${INPUT_FILE_NAME}" \
-        "${format}" \
-        "$suffix");
-    local log=$(compute_if_empty "${PASS_LOG_FILE_PREFIX}" \
+        "${OUTPUT_DIR_NAME}"  \
+        "${suffix}" \
+        "${format}" );
+    local pass_log_file_prefix=$(compute_if_empty \
+        "${PASS_LOG_FILE_PREFIX}" \
         "${INPUT_FILE_NAME}" \
-        "pass" \
-        "$suffix");
-    verbose_start "profile ${name,,} $suffix $format";
+        "${OUTPUT_DIR_NAME}"  \
+        "${suffix}");
+    verbose_start "profile n=${name,,} s=${suffix} f=${format}";
 
     local global_options="";
     global_options+=$(if_exists ' -t %s' ${FFMPEG_TIME})
@@ -98,7 +102,7 @@ handle_profile(){
     for pass in $(seq 1 ${passes}); do
         local pass_options="";
         if [[ ${passes} > 1 ]]; then
-            pass_options="-pass ${pass} -passlogfile  ${log}";
+            pass_options="-pass ${pass} -passlogfile  ${pass_log_file_prefix}";
         fi;
         verbose_run "ffmpeg:%4s" ${FFMPEG_BIN} \
             ${global_options} \
@@ -106,10 +110,10 @@ handle_profile(){
             ${video_options} \
             ${pass_options} \
             ${audio_options} \
-            -f ${format} -y ${output};
+            -f ${format} -y ${output_out_file_name};
     done
     verbose_end "passes:%2s";
-    verbose_end "profile";
+    verbose_end "profile n=${name,,} s=${suffix} f=${format}";
 }
 
 
@@ -294,25 +298,40 @@ get () {
 # ------------------------------------------------------------
 
 compute_if_empty (){
-    local file_name="${1}";
-    if [[ -z "${file_name}" ]] ; then
-        local initial_name="${2}";
-        local extention="${3}";
+    local out_file_name="${1}";
+    if [[ -z "${out_file_name}" ]] ; then
+        local initial_file_name="${2}";
+        local out_dir_name="${3}";
         local suffix="${4}";
-        assert_not_empty "${initial_name}" "empty base name";
-        local base_name=${initial_name%.*};
+        local extention="${5}";
+        assert_not_empty "${initial_file_name}" "empty base name";
+        local base_file_name=$(basename "${initial_file_name}");
+        local base_name=${base_file_name%.*};
         if [[ -z "${extention}" ]] ; then
-            extention="${initial_name##*.}"
+            extention="${base_file_name##*.}"
+            extention="${extention,,}"
         fi;
-        file_name="${base_name}-${suffix}.${extention}"
+        notice 's1';
+
+        if [[ ! -d "${out_dir_name}" ]]; then
+            echo 'ssss'
+
+        fi;
+
+        out_file_name="${base_name}.${extention}"
+        if [[ -n "${suffix}" ]] ; then
+            out_file_name="${base_name}-${suffix}.${extention}"
+        fi;
+
+
     fi;
-    echo "${file_name}";
+    echo "${out_file_name}";
 }
 
 assert_not_empty () {
-    local file_name="${1}";
+    local out_file_name="${1}";
     local message="${2}";
-    if [[ -z "${file_name}" ]] ; then
+    if [[ -z "${out_file_name}" ]] ; then
         wrong_usage "${message}";
     fi;
 }
@@ -323,9 +342,9 @@ assert_not_empty () {
 
 configure () {
     parse_options "${@}";
-    local file_name="${CONFIG_FILE_NAME}";
-    if [[ -n "${file_name}" ]]; then
-        handle_config "${file_name}";
+    local out_file_name="${CONFIG_FILE_NAME}";
+    if [[ -n "${out_file_name}" ]]; then
+        handle_config "${out_file_name}";
     else
         default_config;
     fi;
@@ -333,9 +352,11 @@ configure () {
 
 parse_options (){
 
-    local OPTIONS=$(getopt -o hi:o:c:vqd \
-        --long 'help,input:,output:config:,verbose,quiet,dry-run' \
-        -n "$0" -- "${@}");
+    local OPTIONS=$(getopt -o i:o:O:c:hvqd          \
+        --long                                      \
+            'input:,output:,output-dir:,config:,'   \
+            'help,verbose,quiet,dry-run'            \
+         "$0" -- "${@}");
 
     #set -- ${OPTIONS};
 
@@ -360,6 +381,15 @@ parse_options (){
                     *)
                         OUTPUT_FILE_NAME=${2};
                         readonly OUTPUT_FILE_NAME;
+                        shift 2;;
+                esac;;
+            -O|--output-dir)
+                case "${2}" in
+                    '')
+                        shift 1;;
+                    *)
+                        OUTPUT_DIR_NAME=${2};
+                        readonly OUTPUT_DIR_NAME;
                         shift 2;;
                 esac;;
             -c|--config)
@@ -435,6 +465,83 @@ parse_config() {
 # Printing functions
 # ------------------------------------------------------------
 
+
+if [ -t 2 ]; then
+    # Сброс
+    Color_Off='\e[0m'       # Text Reset
+
+
+    # Обычные цвета
+    Black='\e[0;30m'        # Black
+    Red='\e[0;31m'          # Red
+    Green='\e[0;32m'        # Green
+    Yellow='\e[0;33m'       # Yellow
+    Blue='\e[0;34m'         # Blue
+    Purple='\e[0;35m'       # Purple
+    Cyan='\e[0;36m'         # Cyan
+    White='\e[0;37m'        # White
+
+    # Жирные
+    BBlack='\e[1;30m'       # Black
+    BRed='\e[1;31m'         # Red
+    BGreen='\e[1;32m'       # Green
+    BYellow='\e[1;33m'      # Yellow
+    BBlue='\e[1;34m'        # Blue
+    BPurple='\e[1;35m'      # Purple
+    BCyan='\e[1;36m'        # Cyan
+    BWhite='\e[1;37m'       # White
+
+    # Подчёркнутые
+    UBlack='\e[4;30m'       # Black
+    URed='\e[4;31m'         # Red
+    UGreen='\e[4;32m'       # Green
+    UYellow='\e[4;33m'      # Yellow
+    UBlue='\e[4;34m'        # Blue
+    UPurple='\e[4;35m'      # Purple
+    UCyan='\e[4;36m'        # Cyan
+    UWhite='\e[4;37m'       # White
+
+    # Фоновые
+    On_Black='\e[40m'       # Black
+    On_Red='\e[41m'         # Red
+    On_Green='\e[42m'       # Green
+    On_Yellow='\e[43m'      # Yellow
+    On_Blue='\e[44m'        # Blue
+    On_Purple='\e[45m'      # Purple
+    On_Cyan='\e[46m'        # Cyan
+    On_White='\e[47m'       # White
+
+    # Высоко Интенсивные
+    IBlack='\e[0;90m'       # Black
+    IRed='\e[0;91m'         # Red
+    IGreen='\e[0;92m'       # Green
+    IYellow='\e[0;93m'      # Yellow
+    IBlue='\e[0;94m'        # Blue
+    IPurple='\e[0;95m'      # Purple
+    ICyan='\e[0;96m'        # Cyan
+    IWhite='\e[0;97m'       # White
+
+    # Жирные Высоко Интенсивные
+    BIBlack='\e[1;90m'      # Black
+    BIRed='\e[1;91m'        # Red
+    BIGreen='\e[1;92m'      # Green
+    BIYellow='\e[1;93m'     # Yellow
+    BIBlue='\e[1;94m'       # Blue
+    BIPurple='\e[1;95m'     # Purple
+    BICyan='\e[1;96m'       # Cyan
+    BIWhite='\e[1;97m'      # White
+
+    # Высоко Интенсивные фоновые
+    On_IBlack='\e[0;100m'   # Black
+    On_IRed='\e[0;101m'     # Red
+    On_IGreen='\e[0;102m'   # Green
+    On_IYellow='\e[0;103m'  # Yellow
+    On_IBlue='\e[0;104m'    # Blue
+    On_IPurple='\e[0;105m'  # Purple
+    On_ICyan='\e[0;106m'    # Cyan
+    On_IWhite='\e[0;107m'   # White
+fi;
+
 show_usage(){
     usage;
     exit 0;
@@ -447,7 +554,7 @@ wrong_usage(){
 }
 
 verbose() {
-    [[ "x${VERBOSE}" = "xtrue" ]] && printf "# ${@}\n" 1>&2;
+    [[ "x${VERBOSE}" = "xtrue" ]] && printf "${BIGreen}#${Color_Off} ${@}\n" 1>&2;
 }
 
 verbose_offset (){
@@ -455,7 +562,7 @@ verbose_offset (){
 }
 
 verbose_inside (){
-    verbose_offset "${1}%2s" "${2}";
+    verbose_offset "${1}  " "${2}";
 }
 
 verbose_start (){
@@ -463,7 +570,7 @@ verbose_start (){
     local delimiter=':';
     local name=$(awk -F "$delimiter" '{print $1}' <<< "$string")
     local offset=$(awk -F "$delimiter" '{print $2}' <<< "$string")
-    verbose_offset "${offset}" "<${name}>";
+    verbose_offset "${offset}" "${IPurple}<${name}>${Color_Off}";
 }
 
 verbose_end (){
@@ -471,7 +578,7 @@ verbose_end (){
     local delimiter=':';
     local name=$(awk -F "$delimiter" '{print $1}' <<< "$string")
     local offset=$(awk -F "$delimiter" '{print $2}' <<< "$string")
-    verbose_offset "${offset}" "</${name}>";
+    verbose_offset "${offset}" "${IPurple}</${name}>${Color_Off}";
 }
 
 verbose_block (){
@@ -480,7 +587,7 @@ verbose_block (){
     local offset=$(awk -F "$delimiter" '{print $2}' <<< "$string")
     local value=${@:2}
     verbose_start "${string}"
-    verbose_inside "${offset}" "${value}";
+    verbose_inside "${offset}" "${BICyan}${value}${Color_Off}";
     verbose_end "${string}";
 }
 
@@ -491,7 +598,7 @@ verbose_run (){
     local offset=$(awk -F "$delimiter" '{print $2}' <<< "$string")
     local value=${@:2}
     verbose_start "${string}"
-    verbose_inside "${offset}" "${value}";
+    verbose_inside "${offset}" "${BIYellow}${value}${Color_Off}";
     if [[ "x${DRY_RUN}" = "xfalse" ]]; then
         if [[ "x${VERBOSE}" = "xtrue" ]]; then
             eval "${value}";
@@ -503,23 +610,23 @@ verbose_run (){
 }
 
 success () {
-    echo -e "SUCCESS:${PROGNAME}: ${@}" 1>&2;
+    echo -e "${BIGreen}SUCCESS:${Color_Off} ${0}: ${BIGreen}${@}${Color_Off}" 1>&2;
 }
 
 fail () {
-    echo -e "FAIL:${PROGNAME}: ${@}" 1>&2;
+    echo -e "${BIRed}FAIL:${Color_Off} ${0}: ${BIRed}${@}${Color_Off}" 1>&2;
 }
 
 warn () {
-    echo -e "WARN:${PROGNAME}: ${@}" 1>&2;
+    echo -e "${BIYellow}WARN:${Color_Off} ${0}: ${BIYellow}${@}${Color_Off}" 1>&2;
 }
 
 error () {
-    echo -e "ERROR:${PROGNAME}: ${@}" 1>&2;
+    echo -e "${BIRed}ERROR:${Color_Off} ${0}: ${BIRed}${@}${Color_Off}" 1>&2;
 }
 
 notice() {
-    echo -e "${@}" 1>&2;
+    echo -e "${On_Blue}${BICyan} NOTICE:${Color_Off} ${0}: ${BICyan}${@}${Color_Off}" 1>&2;
 }
 
 
